server:
  port: 0
  servlet:
    context-path: /auth


spring:
  application.name: auth-service


jwt:
  secret: fdjsgtolkeworuj435i23jhsfesrhf4isaf4iwelrujweailuhfd34wiuryheuafhkseuhfd,dsruyr3w4irekuahdfeiuwrhfkdsfhniwe4lrhiafhsjkdshfjkeshirfu
  expiration: 86400

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
