server:
  port: 0
  servlet:
    context-path: /auth


spring:
  application.name: auth-service


jwt:
  secret: fdjsgtolkeworuj435i23jhsfesrhf4isaf4iwelrujweailuhfd34wiuryheuafhkseuhfd,dsruyr3w4irekuahdfeiuwrhfkdsfhniwe4lrhiafhsjkdshfjkeshirfu
  expiration: 86400

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
