server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: gateway-service
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: service-user-id
          uri: lb://service-user
          predicates:
            Path=/user/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
