server:
  port: 8080
  error:
    include-message: always
#    include-exception: true

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application.name: gateway-service
  cloud:
    gateway:
      set-status:
        original-status-header-name: original-http-status
      discovery.locator.enabled: true
      routes:
        - id: user-service-id
          uri: lb://user-service
          predicates:
            Path=/user/**
          filters:
            - AuthFilter
        - id: auth-service-id
          uri: lb://auth-service
          predicates:
            Path=/auth/**
        - id: post-service-id
          uri: lb://post-service
          predicates:
            Path=/post/**
          filters:
            - AuthFilter
        - id: graphql-service-id
          uri: lb://graphql-service
          predicates:
            Path=/graphql
          filters:
            - AuthFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
