server:
  port: 0
  servlet:
    context-path: /graphql


graphql:
  url: /graphql

spring:
  application.name: graphql-service
  cloud:
    config:
      uri: http://localhost:8888/config
    stream:
      bindings:
        test-in-0.destination: testQueue
      binder:
        brokers: localhost:9092

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    reactor.netty.http: debug
    graphql.execution.reactive: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
