server:
  port: 0
  servlet:
    context-path: /graphql


graphql:
  url: /graphql

spring:
  application.name: graphql-service

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    reactor.netty.http: debug
    graphql.execution.reactive: debug

