server:
  port: 0
  servlet:
    context-path: /graphql


graphql:
  url: /graphql

spring:
  application.name: graphql-service
  cloud:
    stream:
      bindings:
        consumer-in-0.destination: postCreated
      binder:
        brokers: localhost:9092

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    reactor.netty.http: debug
    graphql.execution.reactive: debug

