server:
  port: 8888
  servlet:
    context-path: /config

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint:
    health:
      probes.enabled: true
      show-details: always

spring:
  profiles:
    active: git, native
  application.name: config-service
  cloud:
    config:
      server:
        git:
          #          uri: file://${user.home}/personal/config-repo
          uri: git@github.com:NeNaO4ke/config-repo.git
          default-label: main
          order: 2
        native:
          search-locations: classpath:/config/
          order: 1



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
